### ISSUE TITLE
How to mock static methods?

### ISSUE THREAD

**Issue by Bargath** [nbuesing/gwtMockitoExample#1]
I have a class like this:

public class Utilities{
public static int getValue(){
return 10;
}
}

I want to write test for this class:

public class ServiceClass{
public void populate(){
if(Utilities.getValue() < 15){

}
}
}

Is it possible to mock what Utilities.getValue() return?

**Comment by nbuesing** [comment]
If I'm in control of the code, I try not to write code like that where I need to change behavior via mocking.  If you absolutely need to do something like this, you will want to look into PowerMock.
